env:
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
 
name: CI-CD
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:      
     - name: Checkout
       uses: actions/checkout@v4.1.5 

     - name: Docker Login  
       uses: docker/login-action@v3.1.0
       with:
         username: ${{ secrets.DK_USER }}
         password: ${{ secrets.DK_PWD }}
         
     - name: Set up JDK 17
       uses: actions/setup-java@v1
       with:
         java-version: 17
         distribution: 'adopt'
         cache: maven

     - name: Build with maven
       run: mvn clean install -Dskiptests
         
     - name: Build and push Docker images
       uses: docker/build-push-action@v5.3.0
       with:
         context: .
         file: Dockerfile
         push: true
         tags: |
           ${{ secrets.DK_USER }}/spring-boot-to-do-list:${{  github.run_number  }}
           ${{ secrets.DK_USER }}/spring-boot-to-do-list:latest
        
