env:
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}

name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:      
     - name: Checkout
       uses: actions/checkout@v4.1.5 

     - name: Docker Login  
       uses: docker/login-action@v3.1.0
       with:    
         username: ${{  secrets.DOCKER_USERNAME  }}             
         password: ${{  secrets.DOCKER_PWD  }}   
                   
     - name: Build and push Docker images
       uses: docker/build-push-action@v5.3.0
       with:
         context: .
         file: Dockerfile
         push: true
         tags: |
           ${{ secrets.DOCKER_USERNAME }}/spring-boot-to-do-list:{{  github.run_number  }}
           ${{ secrets.DOCKER_USERNAME }}/spring-boot-to-do-list:latest
